version: '3.8'
services:
  db:
    container_name: postgres
    restart: always
    image: postgres:15.1-alpine
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres